[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.12"
engine = { path = "../engine" }
render = { path = "../render" }
entities = { path = "../entities" }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"